# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microblog', '0002_auto_20160928_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='content',
            field=models.CharField(max_length=140, verbose_name='My post'),
        ),
    ]
