# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='following',
            field=models.ManyToManyField(related_name='followers', to='custom_accounts.UserProfile'),
        ),
    ]
