# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 16:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user',
            new_name='user_model',
        ),
    ]
